### ISSUE TITLE
bug(framework): kubectl_manifest no longer supports terraform import (regression from #318)

### ISSUE THREAD

**Issue by alekc** [alekc/terraform-provider-kubectl#326]
## Summary

`terraform import kubectl_manifest.<name> <id>` no longer works on v3 (master). The pre-Phase-F SDK v2 resource implemented a full `Importer.StateContext` that parsed `apiVersion//kind//name` and `apiVersion//kind//name//namespace` IDs, fetched the live object via the dynamic client, and populated the resource's computed fields. The framework rewrite (PR #318, commit `13fb804`) did not port the `Importer`; `internal/framework/resource_kubectl_manifest.go` does not implement `resource.ResourceWithImportState`, so any `terraform import` invocation against a `kubectl_manifest` now fails with the framework's default "this resource does not support import" diagnostic.

This is a silent regression. Users discovering it have a configured manifest under management externally, run `terraform import` to bring it under Terraform, and get a hard error instead. The documented behaviour at `docs/resources/kubectl_manifest.md:261-271` still advertises import as supported.

## Pre-cutover behaviour

`kubernetes/resource_kubectl_manifest.go:135-228` (pre-Phase-F, retrievable via `git show 13fb804^:kubernetes/resource_kubectl_manifest.go`) declared:

```go
Importer: &schema.ResourceImporter{
    StateContext: func(ctx context.Context, d *schema.ResourceData, meta interface{}) ([]*schema.ResourceData, error) {
        // parses apiVersion//kind//name[//namespace], dynamic-client Get,
        // populates uid, live_uid, yaml_incluster, live_manifest_incluster,
        // api_version, kind, namespace, name, force_new=false,
        // server_side_apply=false, apply_only=false, upgrade_api_version=false,
        // plus a stripped yaml_body / yaml_body_parsed
    },
},
```

This matches the upstream `gavinbunney/kubectl` import shape.

## Post-cutover behaviour

```
$ grep -rn "ResourceWithImportState\|resource.ImportState\|ImportStatePassthrough" internal/framework/
# no matches
```

`internal/framework/resource_kubectl_manifest.go` defines `manifestResource` without `ImportState`. Result: `terraform import` against `kubectl_manifest` fails at the framework gateway before any provider code runs.

## Reproduction

```hcl
resource "kubectl_manifest" "ns" {
  yaml_body = yamlencode({
    apiVersion = "v1"
    kind       = "Namespace"
    metadata   = { name = "imported-ns" }
  })
}
```

```sh
kubectl create namespace imported-ns
terraform import kubectl_manifest.ns 'v1//Namespace//imported-ns'
# Error: Resource Import Not Implemented
```

## Suggested fix sketch

Implement `ImportState` on `manifestResource` (the framework analogue of the deleted SDK v2 `StateContext`). Parse `req.ID` with the same `//` delimiter convention, build a minimal manifest YAML for the dynamic-client `Get`, set the same fields on `resp.State` that the v2 importer populated. The post-Read consistency machinery already in `manifestResource.Read` should cover the rest. Wire the resource into `resource.ResourceWithImportState`. Add an acceptance test that imports a Namespace (cluster-scoped) and a namespaced object (e.g. ConfigMap or CRD instance) so both ID shapes are covered.

## References

- PR #318 (Phase F, framework-only provider): the cutover that dropped it
- Audit: discovered alongside PR #324 (apply_retry_count restore), which fixed the sister regression of "schema kept, behaviour dropped"
- Pre-cutover code: `git show 13fb804^:kubernetes/resource_kubectl_manifest.go` lines 135-228
- Docs still advertising support: `docs/resources/kubectl_manifest.md:261-271`

Labels: bug
