### PR TITLE
fix(framework): restore terraform import support for kubectl_manifest

### LINKED ISSUE #326: bug(framework): kubectl_manifest no longer supports terraform import (regression from #318)
## Summary

`terraform import kubectl_manifest.<name> <id>` no longer works on v3 (master). The pre-Phase-F SDK v2 resource implemented a full `Importer.StateContext` that parsed `apiVersion//kind//name` and `apiVersion//kind//name//namespace` IDs, fetched the live object via the dynamic client, and populated the resource's computed fields. The framework rewrite (PR #318, commit `13fb804`) did not port the `Importer`; `internal/framework/resource_kubectl_manifest.go` does not implement `resource.ResourceWithImportState`, so any `terraform import` invocation against a `kubectl_manifest` now fails with the framework's default "this resource does not support import" diagnostic.

This is a silent regression. Users discovering it have a configured manifest under management externally, run `terraform import` to bring it under Terraform, and get a hard error instead. The documented behaviour at `docs/resources/kubectl_manifest.md:261-271` still advertises import as supported.

## Pre-cutover behaviour

`kubernetes/resource_kubectl_manifest.go:135-228` (pre-Phase-F, retrievable via `git show 13fb804^:kubernetes/resource_kubectl_manifest.go`) declared:

```go
Importer: &schema.ResourceImporter{
    StateContext: func(ctx context.Context, d *schema.ResourceData, meta interface{}) ([]*schema.ResourceData, error) {
        // parses apiVersion//kind//name[//namespace], dynamic-client Get,
        // populates uid, live_uid, yaml_incluster, live_manifest_incluster,
        // api_version, kind, namespace, name, force_new=false,
        // server_side_apply=false, apply_only=false, upgrade_api_version=false,
        // plus a stripped yaml_body / yaml_body_parsed
    },
},
```

This matches the upstream `gavinbunney/kubectl` import shape.

## Post-cutover behaviour

```
$ grep -rn "ResourceWithImportState\|resource.ImportState\|ImportStatePassthrough" internal/framework/
# no matches
```

`internal/framework/resource_kubectl_manifest.go` defines `manifestResource` without `ImportState`. Result: `terraform import` against `kubectl_manifest` fails at the framework gateway before any provider code runs.

## Reproduction

```hcl
resource "kubectl_manifest" "ns" {
  yaml_body = yamlencode({
    apiVersion = "v1"
    kind       = "Namespace"
    metadata   = { name = "imported-ns" }
  })
}
```

```sh
kubectl create namespace imported-ns
terraform import kubectl_manifest.ns 'v1//Namespace//imported-ns'
# Error: Resource Import Not Implemented
```

## Suggested fix sketch

Implement `ImportState` on `manifestResource` (the framework analogue of the deleted SDK v2 `StateContext`). Parse `req.ID` with the same `//` delimiter convention, build a minimal manifest YAML for the dynamic-client `Get`, set the same fields on `resp.State` that the v2 importer populated. The post-Read consistency machinery already in `manifestResource.Read` should cover the rest. Wire the resource into `resource.ResourceWithImportState`. Add an acceptance test that imports a Namespace (cluster-scoped) and a namespaced object (e.g. ConfigMap or CRD instance) so both ID shapes are covered.

## References

- PR #318 (Phase F, framework-only provider): the cutover that dropped it
- Audit: discovered alongside PR #324 (apply_retry_count restore), which fixed the sister regression of "schema kept, behaviour dropped"
- Pre-cutover code: `git show 13fb804^:kubernetes/resource_kubectl_manifest.go` lines 135-228
- Docs still advertising support: `docs/resources/kubectl_manifest.md:261-271`

Labels: bug

### PR DESCRIPTION
**Pull request by alekc**
## Summary

Restores `terraform import` support for `kubectl_manifest`. PR #318 (Phase F, commit `13fb804`) ported the resource from SDK v2 to the plugin framework but did not port the SDK v2 `Importer.StateContext`. As a result `terraform import kubectl_manifest.<name> <id>` failed with the framework's default "Resource Import Not Implemented" diagnostic, even though `docs/resources/kubectl_manifest.md:261-271` still advertised import as supported. This is one of the v2 to v3 regressions surfaced by the audit alongside PR #324 (`apply_retry_count` restore).

Fixes: #326.

## What changes

Adds `ImportState` to the framework `manifestResource` as the analogue of the deleted SDK v2 importer, plus the matching `_ resource.ResourceWithImportState = (*manifestResource)(nil)` interface assertion.

The importer keeps the documented ID format: `apiVersion//kind//name[//namespace]`. The double-slash delimiter is load-bearing because apiVersion can contain a single slash (`apps/v1`, `cert-manager.io/v1`, etc.).

End-to-end shape:

1. Parse `req.ID`. Reject malformed input (wrong part count, empty component) with a clear `kubectl_manifest Import: malformed ID` diagnostic.
2. Discover the GVK via `kubernetes.GetRestClientFromUnstructuredWithContext` (the ctx-aware variant added in PR #324). Cancellation of `terraform import` now short-circuits the 60s discovery timer instead of blocking on it.
3. `Get` the live object via the dynamic client. Fail clearly if the returned UID is empty (refuse to import an unidentifiable object).
4. Strip `metadata.creationTimestamp`, `metadata.resourceVersion`, `metadata.selfLink`, `metadata.uid`, and the `kubectl.kubernetes.io/last-applied-configuration` annotation so `yaml_body` represents user-controllable fields only. Mirrors the SDK v2 importer.
5. Populate the resource model from the cluster: `id`, `uid`, `live_uid`, `yaml_incluster`, `live_manifest_incluster`, `api_version`, `kind`, `namespace`, `name`, `yaml_body`, `yaml_body_parsed`. `id` uses `Manifest.GetSelfLink()` which already handles the k8s 1.20+ no-selfLink case via the same synthesizer Apply uses.
6. Set Optional+Computed booleans / strings to their schema defaults (`force_new=false`, `upgrade_api_version=false`, `server_side_apply=false`, `field_manager="kubectl"`, `force_conflicts=false`, `apply_only=false`, `wait=false`, `wait_for_rollout=true`, `validate_schema=true`) so the next plan against an unmodified config sees no drift. Fields without a schema default (`override_namespace`, `sensitive_fields`, `ignore_fields`, `delete_cascade`, `timeouts`, `wait_for`) stay null.

## Tests

Two new files under `internal/framework/`:

- `resource_kubectl_manifest_import_test.go`: table-driven unit tests for `parseManifestImportID` (8 cases: cluster-scoped, namespaced, slashed apiVersion, too few parts, too many parts, three empty-component cases) and `buildManifestImportYAMLStub` (cluster-scoped omits namespace, namespaced includes it). 10 sub-tests total, all green locally.
- `resource_kubectl_manifest_import_acc_test.go`: three acceptance tests gated behind `testAccPreCheck`. `TestAccKubectl_ImportClusterScoped` creates a `Namespace` and imports it via a 3-part ID. `TestAccKubectl_ImportNamespaced` creates a `Namespace` + `ConfigMap` and imports the `ConfigMap` via a 4-part ID. `TestAccKubectl_ImportMalformedID` exercises the parser error path with `ExpectError`. All three use `ImportStateVerify: true` with `ImportStateVerifyIgnore: ["yaml_body", "yaml_body_parsed"]` because the importer rebuilds those from the stripped live object (key order and quoting will differ from the user's input) while the fingerprints (`yaml_incluster` / `live_manifest_incluster`) already pin the semantic equivalence.

`go build ./...`, `go vet ./...`, and `go test ./... -short -count=1` pass locally. The acceptance tests run in the existing CI matrix (Terraform 1.5 to 1.15, OpenTofu 1.7 to 1.11, k8s 1.32 to 1.36).

## Reference

- Pre-cutover importer: `git show 13fb804^:kubernetes/resource_kubectl_manifest.go` lines 135-228.
- Phase F cutover: PR #318.
- Sister regression fixed: PR #324 (`apply_retry_count`). The same "schema kept, behaviour dropped during the SDK v2 to framework cutover" shape.
- Audit context: #326 was filed alongside #327-#330 from the post-#324 audit of v2 to v3 contract changes.

## Summary by CodeRabbit

* **New Features**
  * Import existing Kubernetes manifests into Terraform state using structured import IDs for cluster-scoped and namespaced resources.
  * Live object fetch produces a cleaned YAML snapshot: system metadata stripped, Secret data defaults obfuscated, and live fingerprints recorded.
  * Schema-defaults applied to avoid spurious plan drift after import.

* **Tests**
  * Added unit and acceptance tests covering import ID parsing, YAML discovery stubs, successful imports, and malformed-ID handling.

### CODE REVIEW

File: internal/framework/resource_kubectl_manifest.go [hunk 1]
```diff
@@ -936,3 +941,174 @@ func stringOrDefault(s types.String, fallback string) string {
...
+	data.Kind = types.StringValue(live.GetKind())
+	data.Name = types.StringValue(live.GetName())
+	if live.GetNamespace() != "" {
+		data.Namespace = types.StringValue(live.GetNamespace())
+	} else {
+		data.Namespace = types.StringNull()
+	}
+	data.YAMLBody = types.StringValue(yamlStripped)
+	data.YAMLBodyParsed = types.StringValue(yamlStripped)
+
```
[the remark this answers is not in the document]
Comment (alekc) [reply internal/framework/resource_kubectl_manifest.go:1088]: check again
